Test:
  test: test_11_22

mysql:
  config: {"host":"api.lemonban.com",
           "user":"future",
           "password":"123456",
           "port":3306,
           "db":"futureloan",
           "charset":"utf8"}
  sql:  "select * from member where mobile_phone = %s" # %s 占位符，官方推荐方法，防止sql注入问题，所以不用format,cursor.execute(sql,args=[%s])
  sql_no_exist_id: "SELECT id FROM member ORDER BY id DESC LIMIT 0,1;"  # "select max(id) from member;"
  sql_no_exist_loan_id: "SELECT id FROM loan ORDER BY id DESC LIMIT 0,1;"


mylogger:
  fmt: "%(name)s--%(asctime)s--%(levelname)s--[levelno:%(levelno)s]--%(message)s"
  datefmt: "%a_%Y/%m/%d_%H:%M:%S"
  logname: mylogger
  collect_level: DEBUG
  output_level: DEBUG


excel:
  sheet1_name: register
  sheet2_name: login
  sheet3_name: recharge
  sheet4_name: add
  sheet5_name: invest

  result_column: result
  actul_column: actul

  pass_value: PASS
  fail_value: FAIL


requests:
  headers: {"X-Lemonban-Media-Type":"lemonban.v2","Content-Type":"application/json","User-Agent": "Mozilla/5.0 KeYou"}
  url: "http://api.lemonban.com/futureloan"

report:
  tester: zhicheng
  title: Auto_api
